modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="${mod_issues}"
license="GPLv3"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
license="GPL-3"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="catlib.neoforge.mixins.json"
[[mixins]]
config="catlib.common.mixins.json"
